### PR TITLE
Cancel execution by timeout

### PR DESCRIPTION
**Pull request by shajyhia**
cancel execution by interrupting its thread

### CODE REVIEW

**Comment by shajyhia** [comment]
review by Natasha

**Comment by orius123** [comment]
This class just keeps getting prettier..

**Comment by oritstone** [comment]
Going to open an issue of refactoring it...

**Comment by natabeck** [comment]
I will merge all the termination cases into one once I get to this class... Then at least the loop's if will be a bit smaller...

**Comment by oritstone** [comment]
Also the methods such as `isExecutionCancelled()` should return true\false, but should not also cancel the execution...

**Pull request merged**
